FROM geerlingguy/docker-debian9-ansible
LABEL maintainer="AnarchoTech NYC"
RUN apt-get update && apt-get install --yes --no-install-recommends \
    python3 python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && rm -Rf /usr/share/doc && rm -Rf /usr/share/man \
    && apt-get clean \
    && pip3 install setuptools
